"""added creator relation to Post scheme

Revision ID: 9fc2938e7cab
Revises: 6a716d7a9159
Create Date: 2021-09-25 20:33:13.106808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fc2938e7cab'
down_revision = '6a716d7a9159'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
