"""User added

Revision ID: d476d54ac090
Revises: 8e74633e66f5
Create Date: 2021-09-23 13:10:41.057818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd476d54ac090'
down_revision = '8e74633e66f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
